apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: hatena-intern-2022
build:
  artifacts:
  - image: hatena-intern-2022-account
    context: services/account
  - image: hatena-intern-2022-account-test
    context: services/account
    docker:
      dockerfile: Dockerfile.test
  - image: hatena-intern-2022-blog
    context: services/blog
  - image: hatena-intern-2022-blog-test
    context: services/blog
    docker:
      dockerfile: Dockerfile.test
  - image: hatena-intern-2022-renderer-go
    context: services/renderer-go
  local:
    push: false
    useBuildkit: true
deploy:
  statusCheckDeadlineSeconds: 180
  kubeContext: hatena-intern-2022
  kustomize:
    paths:
    - k8s
portForward:
  - resourceType: service
    resourceName: blog
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: blog-db
    port: 3306
    localPort: 3306
  - resourceType: service
    resourceName: account-db
    port: 3306
    localPort: 3307
  - resourceType: service
    resourceName: account
    port: 50051
    localPort: 50051
  - resourceType: service
    resourceName: renderer-go
    namespace: hatena-intern-2022
    port: 50051
    localPort: 50052
# port-forward設定を追加したい場合、以下に追記
#  - resourceType: service
#    resourceName: renderer-ts
#    namespace: hatena-intern-2022
#    port: 50051
#    localPort: 50053