apiVersion: v1
kind: Service
metadata:
  name: blog-db
  labels:
    app: blog
spec:
  ports:
  - port: 3306
  selector:
    app: blog
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-db-pv-claim
  labels:
    app: blog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-db-initdb-config
data:
  init.sh: |
    #!/bin/bash
    set -ex
    mysqladmin -uroot create intern_2022_blog
    mysqladmin -uroot create intern_2022_blog_test
    mysql -uroot intern_2022_blog < /config/schema.sql
    mysql -uroot intern_2022_blog_test < /config/schema.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-db
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blog
        tier: db
    spec:
      containers:
      - image: mysql/mysql-server:8.0
        name: mysql
        args:
        - --lower-case-table-names=1
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: TZ
          value: UTC
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 300m
            memory: 1Gi
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb-volume
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        - name: mysql-schema-volume
          mountPath: /config
          readOnly: true
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: blog-db-pv-claim
      - name: mysql-initdb-volume
        configMap:
          name: blog-db-initdb-config
          defaultMode: 0755
      - name: mysql-schema-volume
        configMap:
          name: blog-db-schema-config
