// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: fetcher.proto

package fetcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchPageTitleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchPageTitleRequest) Reset() {
	*x = FetchPageTitleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPageTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPageTitleRequest) ProtoMessage() {}

func (x *FetchPageTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPageTitleRequest.ProtoReflect.Descriptor instead.
func (*FetchPageTitleRequest) Descriptor() ([]byte, []int) {
	return file_fetcher_proto_rawDescGZIP(), []int{0}
}

type FetchPageTitleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchPageTitleReply) Reset() {
	*x = FetchPageTitleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPageTitleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPageTitleReply) ProtoMessage() {}

func (x *FetchPageTitleReply) ProtoReflect() protoreflect.Message {
	mi := &file_fetcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPageTitleReply.ProtoReflect.Descriptor instead.
func (*FetchPageTitleReply) Descriptor() ([]byte, []int) {
	return file_fetcher_proto_rawDescGZIP(), []int{1}
}

var File_fetcher_proto protoreflect.FileDescriptor

var file_fetcher_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x61, 0x67, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x67, 0x65, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x59, 0x0a, 0x07, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x67, 0x65,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x67, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x67, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x68, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x2f, 0x48, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x2d,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x2d, 0x32, 0x30, 0x32, 0x32, 0x2f, 0x70, 0x62, 0x2f, 0x67,
	0x6f, 0x2f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_fetcher_proto_rawDescOnce sync.Once
	file_fetcher_proto_rawDescData = file_fetcher_proto_rawDesc
)

func file_fetcher_proto_rawDescGZIP() []byte {
	file_fetcher_proto_rawDescOnce.Do(func() {
		file_fetcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_fetcher_proto_rawDescData)
	})
	return file_fetcher_proto_rawDescData
}

var file_fetcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fetcher_proto_goTypes = []interface{}{
	(*FetchPageTitleRequest)(nil), // 0: fetcher.FetchPageTitleRequest
	(*FetchPageTitleReply)(nil),   // 1: fetcher.FetchPageTitleReply
}
var file_fetcher_proto_depIdxs = []int32{
	0, // 0: fetcher.Fetcher.FetchPageTitle:input_type -> fetcher.FetchPageTitleRequest
	1, // 1: fetcher.Fetcher.FetchPageTitle:output_type -> fetcher.FetchPageTitleReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fetcher_proto_init() }
func file_fetcher_proto_init() {
	if File_fetcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fetcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPageTitleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPageTitleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fetcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fetcher_proto_goTypes,
		DependencyIndexes: file_fetcher_proto_depIdxs,
		MessageInfos:      file_fetcher_proto_msgTypes,
	}.Build()
	File_fetcher_proto = out.File
	file_fetcher_proto_rawDesc = nil
	file_fetcher_proto_goTypes = nil
	file_fetcher_proto_depIdxs = nil
}
