name: Test fetcher-go

on:
  push:
    paths:
      - .github/workflows/fetcher-go.yml
      - services/fetcher-go/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - uses: golangci/golangci-lint-action@v3
      with:
        working-directory: services/fetcher-go
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
      working-directory: services/fetcher-go
    - name: Build
      run: go build -v .
      working-directory: services/fetcher-go
    - name: Test
      run: go test -v ./...
      working-directory: services/fetcher-go
